[package]
name = "zendb-sync"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Portable replication and snapshot protocol records for ZeninDB"

[dependencies]
bincode.workspace = true
zendb-types = { path = "../zendb-types" }
