//! Cell encoding and decoding.
//!
//! `encode_cell` and `decode_cell` handle the Cell-level binary format.
//! Value, Op, and Segment encoding dispatch is generated by `register_types!`.

use crate::{Cell, Hlc, TypeError};

/// Encode a Cell: `Value HLC[12] Sync(1 byte)`.
pub fn encode_cell(cell: &Cell, out: &mut Vec<u8>) -> Result<(), TypeError> {
    crate::encode_value(&cell.value, out)?;
    out.extend_from_slice(cell.hlc.as_bytes());
    let sync_byte = match cell.sync {
        None => 0x00,
        Some(false) => 0x01,
        Some(true) => 0x02,
    };
    out.push(sync_byte);
    Ok(())
}

/// Decode a Cell from bytes. Returns the cell and bytes consumed.
pub fn decode_cell(bytes: &[u8]) -> Result<(Cell, usize), TypeError> {
    let (value, n) = crate::decode_value(bytes)?;
    let rest = &bytes[n..];
    if rest.len() < 13 {
        return Err(TypeError::DecodeError("truncated cell".into()));
    }
    let mut hlc_bytes = [0u8; 12];
    hlc_bytes.copy_from_slice(&rest[..12]);
    let hlc = Hlc::from_bytes(hlc_bytes);
    let sync = match rest[12] {
        0x00 => None,
        0x01 => Some(false),
        0x02 => Some(true),
        b => return Err(TypeError::DecodeError(format!("invalid sync byte: {}", b))),
    };
    Ok((Cell::new(value, hlc, sync), n + 13))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::atom::AtomValue;
    use crate::Value;

    #[test]
    fn encode_decode_cell_roundtrip() {
        let cell = Cell::new(
            Value::Atom(AtomValue::String("hi".into())),
            Hlc::new(100, 0, 1).unwrap(),
            Some(true),
        );
        let mut buf = Vec::new();
        encode_cell(&cell, &mut buf).unwrap();
        let (decoded, consumed) = decode_cell(&buf).unwrap();
        assert_eq!(consumed, buf.len());
        assert_eq!(decoded.hlc, cell.hlc);
        assert_eq!(decoded.sync, Some(true));
    }

    #[test]
    fn encode_decode_op_set_sync() {
        let op = crate::Op::SetSync { sync: Some(false) };
        let mut buf = Vec::new();
        crate::encode_op(&op, &mut buf).unwrap();
        assert_eq!(buf[0], 0xFF);
        assert_eq!(buf[1], 0x01);
        let (decoded, _) = crate::decode_op(&buf).unwrap();
        assert!(matches!(decoded, crate::Op::SetSync { sync: Some(false) }));
    }

    #[test]
    fn encode_decode_op_set_sync_none() {
        let op = crate::Op::SetSync { sync: None };
        let mut buf = Vec::new();
        crate::encode_op(&op, &mut buf).unwrap();
        let (decoded, _) = crate::decode_op(&buf).unwrap();
        assert!(matches!(decoded, crate::Op::SetSync { sync: None }));
    }
}
