[package]
name = "zendb-it"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Integration tests for ZenDB"

[dependencies]
bincode.workspace = true
libp2p-identity.workspace = true
zendb-workspace = { path = "../zendb-workspace", features = ["test-support"] }
zendb-storage = { path = "../zendb-storage" }
zendb-types = { path = "../zendb-types" }

[dev-dependencies]
tempfile = "3"
tracing-subscriber.workspace = true
