[workspace]
resolver = "2"

members = [
    "zendb-types",
    "zendb-storage",
    "zendb-workspace",
    "zendb-it",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/zenin/zendb"
authors = ["ZeninDB Contributors"]

[workspace.dependencies]
# zendb-storage
memmap2 = "0.9"
hashbrown = "0.15"

bincode = { version = "2", features = ["derive"] }

libp2p-identity = { version = "0.2", features = ["ed25519", "peerid", "rand"] }
multiaddr = "0.18"
libp2p = { version = "0.56", features = [
    "dns",
    "ed25519",
    "macros",
    "mdns",
    "noise",
    "quic",
    "tcp",
    "tokio",
    "yamux",
] }
futures = "0.3"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync", "time"] }
rand = "0.8"
tracing = "0.1"

parking_lot = "0.12"
arc-swap = "1"

# zendb-it
tracing-subscriber = { version = "0.3", features = ["fmt"] }
