[package]
name = "zendb-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Storage backends, topics, and invariant-preserving tables for ZenDB"

[dependencies]
memmap2.workspace = true
hashbrown.workspace = true
bincode.workspace = true
arc-swap.workspace = true
parking_lot.workspace = true
zendb-types.workspace = true

[dev-dependencies]
tempfile.workspace = true
