[package]
name = "zendb-workspace"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Catalog, device, and local state lifecycle for ZenDB"

[dependencies]
bincode.workspace = true
parking_lot.workspace = true
zendb-storage = { path = "../zendb-storage" }
zendb-types = { path = "../zendb-types" }
