[package]
name = "zendb-operator"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Optional local operator runtime for ZeninDB workspaces"

[dependencies]
zendb-engine = { path = "../zendb-engine" }
zendb-types = { path = "../zendb-types" }
zendb-storage = { path = "../zendb-storage" }
zendb-replication = { path = "../zendb-replication" }
bincode.workspace = true
blake3.workspace = true
hashbrown.workspace = true
parking_lot.workspace = true
log.workspace = true
rhai = { version = "1", features = ["sync"] }

[dev-dependencies]
futures = "0.3"
zendb-transport = { path = "../zendb-transport" }
