//! Operator run loop: event queue, shutdown state machine, poll + commit.
//!
//! This module owns the async execution logic that drives an operator through
//! its lifecycle. The [`OperatorWorker`] struct in `worker.rs` owns the
//! inputs and spawning; `RunLoop` handles everything that happens after spawn.
//!
//! # Lifecycle events
//!
//! The run loop processes a queue of [`LifecycleEvent`]s before polling for
//! changes. Events are generated by the worker when inputs are attached or
//! detached, or internally when shutdown is triggered.
//!
//! # Shutdown state machine
//!
//! When any lifecycle method returns [`OperatorDirective::Finish`], or an error
//! occurs, the run loop transitions to shutdown:
//!
//! 1. Clear pending events
//! 2. Enqueue `InputClosed` for every remaining input
//! 3. Enqueue `Teardown(reason)`
//! 4. Process the shutdown events sequentially
//! 5. Retire the operator from the database catalog

use std::collections::VecDeque;
use std::sync::{Arc, Weak};

use crate::{runtime::Executor, Database};

use super::{
    worker::OperatorWorker, DispatchConfig, DispatchOperator, OperatorDirective, OperatorPhase,
    TeardownReason,
};

/// Events processed by the run loop in FIFO order.
#[derive(Clone)]
pub(crate) enum LifecycleEvent {
    /// A new input table was attached.
    InputOpened(String),
    /// An input table was detached.
    InputClosed(String),
    /// Teardown the operator permanently.
    Teardown(TeardownReason),
}

/// What the run loop should do after handling a single event or batch.
enum LoopAction {
    /// Advance past the current event.
    AdvanceEvent,
    /// Begin the shutdown sequence with the given phase.
    BeginShutdown(OperatorPhase),
    /// The operator is fully retired — exit the loop.
    Retire(OperatorPhase),
}

/// Encapsulates the shutdown state for an operator.
pub(crate) struct LifecycleState {
    events: VecDeque<LifecycleEvent>,
    phase: Option<OperatorPhase>,
}

impl LifecycleState {
    pub(crate) fn new() -> Self {
        Self {
            events: VecDeque::new(),
            phase: None,
        }
    }

    pub(crate) fn is_shutting_down(&self) -> bool {
        self.phase.is_some()
    }

    pub(crate) fn push_event(&mut self, event: LifecycleEvent) {
        self.events.push_back(event);
    }

    pub(crate) fn begin_shutdown(
        &mut self,
        phase: OperatorPhase,
        input_tables: Vec<String>,
    ) {
        if self.phase.is_some() {
            return;
        }
        self.phase = Some(phase.clone());
        self.events.clear();
        for table in input_tables {
            self.events.push_back(LifecycleEvent::InputClosed(table));
        }
        let reason = phase_to_reason(&phase);
        self.events.push_back(LifecycleEvent::Teardown(reason));
    }

    pub(crate) fn peek(&self) -> Option<&LifecycleEvent> {
        self.events.front()
    }

    pub(crate) fn pop(&mut self) {
        self.events.pop_front();
    }
}

/// Convert an [`OperatorPhase`] to a [`TeardownReason`].
fn phase_to_reason(phase: &OperatorPhase) -> TeardownReason {
    match phase {
        OperatorPhase::Finished => TeardownReason::Finished,
        OperatorPhase::Failed { error } => TeardownReason::Failed {
            error: error.clone(),
        },
        OperatorPhase::Cancelled => TeardownReason::Cancelled,
        OperatorPhase::Active => TeardownReason::Finished,
    }
}

/// Main async run loop. Owns the operator instance after creation and drives
/// it through its lifecycle until retirement or suspension.
pub(crate) async fn run<D>(
    worker: Arc<OperatorWorker<D>>,
    database: Weak<Database<D>>,
    executor: Arc<dyn Executor>,
) where
    D: DispatchOperator,
{
    let config = worker.config();

    // Create the operator instance via DispatchOperator::create.
    let mut operator = match D::create(database.clone(), worker.name(), config).await {
        Ok(op) => op,
        Err(error) => {
            log::error!("operator {:?} create failed: {error}", worker.name());
            worker.begin_shutdown(OperatorPhase::Failed {
                error: error.to_string(),
            });
            retire(&worker, &database, OperatorPhase::Failed { error: error.to_string() }).await;
            return;
        }
    };

    'outer: loop {
        let Some(database_arc) = database.upgrade() else {
            return;
        };
        let runtime = config.runtime_config();

        // --- Process lifecycle events ---
        while let Some(event) = worker.peek_event() {
            match handle_event(&worker, &database, &mut operator, event).await {
                LoopAction::AdvanceEvent => {
                    worker.pop_event();
                }
                LoopAction::BeginShutdown(phase) => {
                    if worker.is_shutting_down() {
                        worker.pop_event();
                    } else {
                        worker.begin_shutdown(phase);
                    }
                    continue 'outer;
                }
                LoopAction::Retire(phase) => {
                    retire(&worker, &database, phase).await;
                    return;
                }
            }
        }

        // --- Suspend if no inputs remain ---
        if !worker.has_inputs() {
            worker.suspend(&database_arc);
            return;
        }

        // --- Poll changes and timers ---
        let changes = worker.poll(runtime.poll_size);
        let timers: Vec<(u64, Vec<u8>)> = worker.drain_timers();
        let db_weak = Arc::downgrade(&database_arc);

        if changes.is_empty() && timers.is_empty() {
            executor.idle().await;
            continue;
        }

        // --- Handle timers ---
        for (fire_at_ms, payload) in timers {
            match operator
                .on_timer(payload, fire_at_ms, db_weak.clone(), worker.name(), config)
                .await
            {
                Ok(OperatorDirective::Continue) => {
                    let _ = database_arc.cancel_timer(worker.name(), fire_at_ms);
                }
                Ok(OperatorDirective::Finish) => {
                    let _ = database_arc.cancel_timer(worker.name(), fire_at_ms);
                    worker.begin_shutdown(OperatorPhase::Finished);
                    continue 'outer;
                }
                Err(error) => {
                    log::error!("operator {:?} on_timer failed: {error}", worker.name());
                    worker.begin_shutdown(OperatorPhase::Failed {
                        error: error.to_string(),
                    });
                    continue 'outer;
                }
            }
        }

        if changes.is_empty() {
            continue;
        }

        // --- Process changes ---
        match operator
            .process(changes, db_weak, worker.name(), config)
            .await
        {
            Ok(OperatorDirective::Continue) => {
                worker.commit();
            }
            Ok(OperatorDirective::Finish) => {
                worker.commit();
                worker.begin_shutdown(OperatorPhase::Finished);
                continue 'outer;
            }
            Err(error) => {
                log::error!("operator {:?} failed: {error}", worker.name());
                worker.begin_shutdown(OperatorPhase::Failed {
                    error: error.to_string(),
                });
                continue 'outer;
            }
        }
    }
}

/// Handle a single lifecycle event, returning the action for the loop.
async fn handle_event<D>(
    worker: &OperatorWorker<D>,
    database: &Weak<Database<D>>,
    operator: &mut D,
    event: LifecycleEvent,
) -> LoopAction
where
    D: DispatchOperator,
{
    let config = worker.config();
    match event {
        LifecycleEvent::InputOpened(table) => {
            match operator
                .on_input_opened(table, database.clone(), worker.name(), config)
                .await
            {
                Ok(OperatorDirective::Continue) => LoopAction::AdvanceEvent,
                Ok(OperatorDirective::Finish) => {
                    LoopAction::BeginShutdown(OperatorPhase::Finished)
                }
                Err(error) => LoopAction::BeginShutdown(OperatorPhase::Failed {
                    error: error.to_string(),
                }),
            }
        }
        LifecycleEvent::InputClosed(table) => {
            match operator
                .on_input_closed(table, database.clone(), worker.name(), config)
                .await
            {
                Ok(OperatorDirective::Continue) => LoopAction::AdvanceEvent,
                Ok(OperatorDirective::Finish) => {
                    LoopAction::BeginShutdown(OperatorPhase::Finished)
                }
                Err(error) => LoopAction::BeginShutdown(OperatorPhase::Failed {
                    error: error.to_string(),
                }),
            }
        }
        LifecycleEvent::Teardown(reason) => {
            let phase = reason_to_phase(&reason);
            match operator
                .teardown(&reason, database.clone(), worker.name(), config)
                .await
            {
                Ok(()) => LoopAction::Retire(phase),
                Err(error) => LoopAction::Retire(OperatorPhase::Failed {
                    error: error.to_string(),
                }),
            }
        }
    }
}

/// Retire the operator from the database.
async fn retire<D>(
    worker: &OperatorWorker<D>,
    database: &Weak<Database<D>>,
    phase: OperatorPhase,
) where
    D: DispatchOperator,
{
    let Some(database) = database.upgrade() else {
        return;
    };
    database.retire_operator(
        worker.name(),
        phase,
        &worker.config().runtime_config().subscriptions,
        Some(worker),
    );
}

/// Convert a [`TeardownReason`] back to an [`OperatorPhase`] for catalog persistence.
fn reason_to_phase(reason: &TeardownReason) -> OperatorPhase {
    match reason {
        TeardownReason::Finished => OperatorPhase::Finished,
        TeardownReason::Failed { error } => OperatorPhase::Failed {
            error: error.clone(),
        },
        TeardownReason::Cancelled => OperatorPhase::Cancelled,
    }
}
