use std::{fmt::Debug, io};

use bincode::{Decode, Encode};

use super::{BoxFuture, Change, OperatorContext, OperatorDirective, OperatorRuntimeConfig};

/// Core operator trait implemented by every concrete operator.
///
/// Each operator declares its own typed [`Config`](Operator::Config) and
/// [`Timer`](Operator::Timer) payload. The generic `D` parameter is the
/// dispatch operator type (the generated `OperatorInstance` enum) and flows
/// through the [`OperatorContext`] so that the operator can interact with the
/// database without knowing its concrete type.
pub trait Operator: Send + 'static {
    type Config: Debug + Clone + PartialEq + Encode + Decode<()> + 'static;
    type Timer: Encode + Decode<()> + 'static;

    fn new(config: &Self::Config) -> io::Result<Self>
    where
        Self: Sized;

    fn open<'a, D>(
        &'a mut self,
        _ctx: OperatorContext<'a, Self, D>,
    ) -> BoxFuture<'a, io::Result<OperatorDirective>>
    where
        D: DispatchOperator,
    {
        Box::pin(async { Ok(OperatorDirective::Continue) })
    }

    fn process<'a, D>(
        &'a mut self,
        changes: Vec<Change>,
        ctx: OperatorContext<'a, Self, D>,
    ) -> BoxFuture<'a, io::Result<OperatorDirective>>
    where
        D: DispatchOperator;

    fn handle_timer<'a, D>(
        &'a mut self,
        _payload: Self::Timer,
        _ctx: OperatorContext<'a, Self, D>,
    ) -> BoxFuture<'a, io::Result<OperatorDirective>>
    where
        D: DispatchOperator,
    {
        Box::pin(async { Ok(OperatorDirective::Continue) })
    }

    fn finish<'a, D>(
        &'a mut self,
        _ctx: OperatorContext<'a, Self, D>,
    ) -> BoxFuture<'a, io::Result<()>>
    where
        D: DispatchOperator,
    {
        Box::pin(async { Ok(()) })
    }
}

/// Config types that carry an [`OperatorRuntimeConfig`].
///
/// The generated `OperatorConfig` struct implements this; every operator-set
/// config is required to so that the database and worker can access retry
/// policy, subscriptions, and poll size generically.
pub trait DispatchOperatorConfig:
    Debug + Clone + PartialEq + Encode + Decode<()> + Send + Sync + 'static
{
    fn runtime_config(&self) -> &OperatorRuntimeConfig;
}

/// Dispatch trait for operator-set enums generated by [`define_operator_set!`].
///
/// `DispatchOperator` is the type-erased specialization of [`Operator`] that
/// the database, worker, and scheduler know about. It forces `Timer = Vec<u8>`
/// so that timers can flow through the system as opaque byte payloads and
/// constrains its `Config` type to implement [`DispatchOperatorConfig`]. The
/// generated `OperatorInstance` enum implements this trait; the macro bridges
/// between the untyped dispatch layer and the typed [`Operator`] methods.
pub trait DispatchOperator: Operator<Timer = Vec<u8>, Config = Self::DispatchConfig> {
    type DispatchConfig: DispatchOperatorConfig;
}
