use std::{fmt::Debug, io, sync::Weak};

use bincode::{Decode, Encode};

use crate::Database;

use super::{BoxFuture, Change, OperatorContext, OperatorDirective, OperatorRuntimeConfig};

/// Core operator trait implemented by every concrete operator.
///
/// Each operator declares its own typed [`Config`](Operator::Config) and
/// [`Timer`](Operator::Timer) payload. The generic `D` parameter is the
/// dispatch operator type (the generated `OperatorInstance` enum) and flows
/// through the [`OperatorContext`] so that the operator can interact with the
/// database without knowing its concrete type.
pub trait Operator: Send + 'static {
    type Config: Debug + Clone + PartialEq + Encode + Decode<()> + 'static;
    type Timer: Encode + Decode<()> + 'static;

    fn new(config: &Self::Config) -> io::Result<Self>
    where
        Self: Sized;

    fn open<'a, D>(
        &'a mut self,
        _ctx: &'a OperatorContext<Self, D>,
    ) -> BoxFuture<'a, io::Result<OperatorDirective>>
    where
        D: DispatchOperator,
    {
        Box::pin(async { Ok(OperatorDirective::Continue) })
    }

    fn process<'a, D>(
        &'a mut self,
        changes: Vec<Change>,
        ctx: &'a OperatorContext<Self, D>,
    ) -> BoxFuture<'a, io::Result<OperatorDirective>>
    where
        D: DispatchOperator;

    fn handle_timer<'a, D>(
        &'a mut self,
        _payload: Self::Timer,
        _fire_at_ms: u64,
        _ctx: &'a OperatorContext<Self, D>,
    ) -> BoxFuture<'a, io::Result<OperatorDirective>>
    where
        D: DispatchOperator,
    {
        Box::pin(async { Ok(OperatorDirective::Continue) })
    }

    fn finish<'a, D>(
        &'a mut self,
        _ctx: &'a OperatorContext<Self, D>,
    ) -> BoxFuture<'a, io::Result<()>>
    where
        D: DispatchOperator,
    {
        Box::pin(async { Ok(()) })
    }
}

/// Config types that carry an [`OperatorRuntimeConfig`].
///
/// The generated `OperatorConfig` struct implements this; every operator-set
/// config is required to so that the database and worker can access retry
/// policy, subscriptions, and poll size generically.
pub trait DispatchOperatorConfig:
    Debug + Clone + PartialEq + Encode + Decode<()> + Send + Sync + 'static
{
    fn runtime_config(&self) -> &OperatorRuntimeConfig;
}

/// Dispatch trait for operator-set enums generated by [`define_operator_set!`].
///
/// `DispatchOperator` is the type-erased dispatch layer that the database,
/// worker, and scheduler know about. Timers flow through this layer as opaque
/// byte payloads, while the generated `OperatorInstance` enum decodes them and
/// delegates to the typed [`Operator`] methods.
pub trait DispatchOperator: Send + 'static {
    type DispatchConfig: DispatchOperatorConfig;

    fn new(config: &Self::DispatchConfig) -> io::Result<Self>
    where
        Self: Sized;

    fn open<'a>(
        &'a mut self,
        db: Weak<Database<Self>>,
        name: &'a str,
        config: &'a Self::DispatchConfig,
    ) -> BoxFuture<'a, io::Result<OperatorDirective>>
    where
        Self: Sized;

    fn process<'a>(
        &'a mut self,
        changes: Vec<Change>,
        db: Weak<Database<Self>>,
        name: &'a str,
        config: &'a Self::DispatchConfig,
    ) -> BoxFuture<'a, io::Result<OperatorDirective>>
    where
        Self: Sized;

    fn handle_timer<'a>(
        &'a mut self,
        payload: Vec<u8>,
        fire_at_ms: u64,
        db: Weak<Database<Self>>,
        name: &'a str,
        config: &'a Self::DispatchConfig,
    ) -> BoxFuture<'a, io::Result<OperatorDirective>>
    where
        Self: Sized;

    fn finish<'a>(
        &'a mut self,
        db: Weak<Database<Self>>,
        name: &'a str,
        config: &'a Self::DispatchConfig,
    ) -> BoxFuture<'a, io::Result<()>>
    where
        Self: Sized;
}
