use std::{fmt::Debug, io, sync::Weak};

use bincode::{Decode, Encode};

use crate::Database;

use super::{BoxFuture, Change, OperatorContext, OperatorDirective, OperatorRuntimeConfig};

/// Core operator trait implemented by every concrete operator.
///
/// Each operator declares its own typed [`Config`](Operator::Config) and
/// [`Timer`](Operator::Timer) payload. The generic `D` parameter is the
/// dispatch operator type (the generated `OperatorInstance` enum) and flows
/// through the [`OperatorContext`] so that the operator can interact with the
/// database without knowing its concrete type.
pub trait Operator: Send + 'static {
    type Config: Debug + Clone + PartialEq + Encode + Decode<()> + 'static;
    type Timer: Encode + Decode<()> + 'static;

    /// Construct the operator from its typed config.
    fn new(config: &Self::Config) -> io::Result<Self>
    where
        Self: Sized;

    /// Called once after construction. The default returns `Continue`.
    fn open<'a, D>(
        &'a mut self,
        ctx: &'a OperatorContext<Self, D>,
    ) -> BoxFuture<'a, io::Result<OperatorDirective>>
    where
        D: DispatchOperator,
    {
        let _ = ctx;
        Box::pin(async { Ok(OperatorDirective::Continue) })
    }

    /// Process a batch of changes. The default is a no-op returning `Continue`.
    fn process<'a, D>(
        &'a mut self,
        changes: Vec<Change>,
        ctx: &'a OperatorContext<Self, D>,
    ) -> BoxFuture<'a, io::Result<OperatorDirective>>
    where
        D: DispatchOperator,
    {
        let _ = (changes, ctx);
        Box::pin(async { Ok(OperatorDirective::Continue) })
    }

    /// Called when a new input table matching the subscription opens.
    fn on_input_opened<'a, D>(
        &'a mut self,
        table: String,
        ctx: &'a OperatorContext<Self, D>,
    ) -> BoxFuture<'a, io::Result<OperatorDirective>>
    where
        D: DispatchOperator,
    {
        let _ = (table, ctx);
        Box::pin(async { Ok(OperatorDirective::Continue) })
    }

    /// Called when a previously open input table closes.
    fn on_input_closed<'a, D>(
        &'a mut self,
        table: String,
        ctx: &'a OperatorContext<Self, D>,
    ) -> BoxFuture<'a, io::Result<OperatorDirective>>
    where
        D: DispatchOperator,
    {
        let _ = (table, ctx);
        Box::pin(async { Ok(OperatorDirective::Continue) })
    }

    /// Called when a registered processing-time timer fires.
    fn handle_timer<'a, D>(
        &'a mut self,
        payload: Self::Timer,
        fire_at_ms: u64,
        ctx: &'a OperatorContext<Self, D>,
    ) -> BoxFuture<'a, io::Result<OperatorDirective>>
    where
        D: DispatchOperator,
    {
        let _ = (payload, fire_at_ms, ctx);
        Box::pin(async { Ok(OperatorDirective::Continue) })
    }

    /// Called on teardown before the worker is removed from memory.
    fn finish<'a, D>(
        &'a mut self,
        ctx: &'a OperatorContext<Self, D>,
    ) -> BoxFuture<'a, io::Result<()>>
    where
        D: DispatchOperator,
    {
        let _ = ctx;
        Box::pin(async { Ok(()) })
    }
}

/// Config types that carry an [`OperatorRuntimeConfig`].
///
/// The generated `OperatorConfig` struct implements this; every operator-set
/// config is required to so that the database and worker can access retry
/// policy, subscriptions, and poll size generically.
pub trait DispatchOperatorConfig:
    Debug + Clone + PartialEq + Encode + Decode<()> + Send + Sync + 'static
{
    fn runtime_config(&self) -> &OperatorRuntimeConfig;

    /// Construct the dispatch config from a typed operator config and runtime
    /// config. The operator type must be part of this dispatch set.
    fn new<O>(config: O::Config, runtime: OperatorRuntimeConfig) -> io::Result<Self>
    where
        O: Operator;
}

/// Dispatch trait for operator-set enums generated by [`define_operator_set!`].
///
/// `DispatchOperator` is the type-erased dispatch layer that the database,
/// worker, and scheduler know about. Timers flow through this layer as opaque
/// byte payloads, while the generated `OperatorInstance` enum decodes them and
/// delegates to the typed [`Operator`] methods.
pub trait DispatchOperator: Send + 'static {
    type DispatchConfig: DispatchOperatorConfig;

    /// Instantiate the concrete operator for this variant.
    fn new(config: &Self::DispatchConfig) -> io::Result<Self>
    where
        Self: Sized;

    /// Called once after construction. Decodes the typed config from the dispatch
    /// config and delegates to [`Operator::open`].
    fn open<'a>(
        &'a mut self,
        db: Weak<Database<Self>>,
        name: &'a str,
        config: &'a Self::DispatchConfig,
    ) -> BoxFuture<'a, io::Result<OperatorDirective>>
    where
        Self: Sized;

    /// Delegates to [`Operator::process`] with the typed context.
    fn process<'a>(
        &'a mut self,
        changes: Vec<Change>,
        db: Weak<Database<Self>>,
        name: &'a str,
        config: &'a Self::DispatchConfig,
    ) -> BoxFuture<'a, io::Result<OperatorDirective>>
    where
        Self: Sized;

    /// Delegates to [`Operator::on_input_opened`].
    fn on_input_opened<'a>(
        &'a mut self,
        table: String,
        db: Weak<Database<Self>>,
        name: &'a str,
        config: &'a Self::DispatchConfig,
    ) -> BoxFuture<'a, io::Result<OperatorDirective>>
    where
        Self: Sized;

    /// Delegates to [`Operator::on_input_closed`].
    fn on_input_closed<'a>(
        &'a mut self,
        table: String,
        db: Weak<Database<Self>>,
        name: &'a str,
        config: &'a Self::DispatchConfig,
    ) -> BoxFuture<'a, io::Result<OperatorDirective>>
    where
        Self: Sized;

    /// Decodes the opaque `payload` bytes and delegates to
    /// [`Operator::handle_timer`].
    fn handle_timer<'a>(
        &'a mut self,
        payload: Vec<u8>,
        fire_at_ms: u64,
        db: Weak<Database<Self>>,
        name: &'a str,
        config: &'a Self::DispatchConfig,
    ) -> BoxFuture<'a, io::Result<OperatorDirective>>
    where
        Self: Sized;

    /// Delegates to [`Operator::finish`] for teardown.
    fn finish<'a>(
        &'a mut self,
        db: Weak<Database<Self>>,
        name: &'a str,
        config: &'a Self::DispatchConfig,
    ) -> BoxFuture<'a, io::Result<()>>
    where
        Self: Sized;
}
